/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download Dataset */
        post: operations["download_dataset_api_datasets_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Rename Project */
        patch: operations["rename_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Definition */
        post: operations["save_definition_api_projects__project_id__definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/definitions/{kind}/{name}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_projects__project_id__definitions__kind___name__draft_get"];
        /** Save Draft */
        put: operations["save_draft_api_projects__project_id__definitions__kind___name__draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Securities */
        get: operations["list_securities_api_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/valuations/comparables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Comparable Valuation */
        post: operations["calculate_comparable_valuation_api_valuations_comparables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/valuations/comparables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Comparable Valuation */
        post: operations["save_comparable_valuation_api_projects__project_id__valuations_comparables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Valuations */
        get: operations["list_saved_valuations_api_projects__project_id__valuations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security Details */
        get: operations["get_security_details_api_securities__security_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Watchlist */
        get: operations["get_project_watchlist_api_projects__project_id__watchlist_get"];
        put?: never;
        /** Add To Project Watchlist */
        post: operations["add_to_project_watchlist_api_projects__project_id__watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/watchlist/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Project Watchlist */
        delete: operations["remove_from_project_watchlist_api_projects__project_id__watchlist__security_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/research/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security Thesis */
        get: operations["get_security_thesis_api_projects__project_id__research__security_id__get"];
        /** Save Security Thesis */
        put: operations["save_security_thesis_api_projects__project_id__research__security_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        /** Import Dataset */
        post: operations["import_dataset_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_version_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coverage */
        get: operations["get_coverage_api_datasets__dataset_version_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_version_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Preview */
        get: operations["get_dataset_preview_api_datasets__dataset_version_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_version_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset History */
        get: operations["get_dataset_history_api_datasets__dataset_version_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_version_id}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Fundamentals */
        get: operations["get_dataset_fundamentals_api_datasets__dataset_version_id__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_version_id}/corporate-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Corporate Actions */
        get: operations["get_dataset_corporate_actions_api_datasets__dataset_version_id__corporate_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_dataset_api_datasets_post */
        Body_import_dataset_api_datasets_post: {
            /** Source */
            source: string;
            /** File */
            file: string;
        };
        /** ComparableCompanyInputResponse */
        ComparableCompanyInputResponse: {
            /** Security Id */
            security_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Market Cap */
            market_cap: number | null;
            /** Total Debt */
            total_debt: number | null;
            /** Cash */
            cash: number | null;
            /** Revenue */
            revenue: number | null;
            /** Ebitda */
            ebitda: number | null;
            /** Net Income */
            net_income: number | null;
            /** Free Cash Flow */
            free_cash_flow: number | null;
            /** Dataset Version Ids */
            dataset_version_ids: string[];
            /** Provenance */
            provenance: {
                [key: string]: string;
            };
            /** Units */
            units: {
                [key: string]: string;
            };
            /** Input Dataset Versions */
            input_dataset_versions: {
                [key: string]: string[];
            };
        };
        /** ComparableCompanyValuationResponse */
        ComparableCompanyValuationResponse: {
            /** Security Id */
            security_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Market Cap */
            market_cap: number | null;
            /** Enterprise Value */
            enterprise_value: number | null;
            /** Price To Earnings */
            price_to_earnings: number | null;
            /** Ev To Revenue */
            ev_to_revenue: number | null;
            /** Ev To Ebitda */
            ev_to_ebitda: number | null;
            /** Free Cash Flow Yield */
            free_cash_flow_yield: number | null;
            inputs: components["schemas"]["ComparableCompanyInputResponse"];
        };
        /** ComparableValuationRequest */
        ComparableValuationRequest: {
            /** Target Security Id */
            target_security_id: string;
            /** Peer Security Ids */
            peer_security_ids: string[];
        };
        /** ComparableValuationResponse */
        ComparableValuationResponse: {
            target: components["schemas"]["ComparableCompanyValuationResponse"];
            /** Peers */
            peers: components["schemas"]["ComparableCompanyValuationResponse"][];
            peer_medians: components["schemas"]["ComparableCompanyValuationResponse"];
            /** Warnings */
            warnings: string[];
            /** Dataset Version Ids */
            dataset_version_ids: string[];
            /** Calculated At */
            calculated_at: string;
            /** Method Revision */
            method_revision?: string | null;
            /** Run Id */
            run_id?: string | null;
        };
        /** CorporateActionResponse */
        CorporateActionResponse: {
            /** Security Id */
            security_id: string;
            /** Type */
            type: string;
            /** Effective Date */
            effective_date: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
            /** Retrieval Time */
            retrieval_time: string;
            /** Available At */
            available_at?: string | null;
            /** Eligibility Provenance */
            eligibility_provenance?: string | null;
            /**
             * Units
             * @default USD
             */
            units: string;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Retrieval Time */
            retrieval_time: string;
            /** Coverage Start */
            coverage_start: string | null;
            /** Coverage End */
            coverage_end: string | null;
            /** Row Count */
            row_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Missing Fields */
            missing_fields: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            /** Total Warnings */
            total_warnings: number;
            /** Files */
            files: string[];
            /**
             * Has Temporal Provenance
             * @default false
             */
            has_temporal_provenance: boolean;
            /**
             * Is Fundamentals
             * @default false
             */
            is_fundamentals: boolean;
            /**
             * Is Corporate Actions
             * @default false
             */
            is_corporate_actions: boolean;
            /**
             * Dataset Type
             * @default daily_bars
             */
            dataset_type: string;
        };
        /** DailyBarResponse */
        DailyBarResponse: {
            /** Security Id */
            security_id: string;
            /** Session Date */
            session_date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Source */
            source: string;
            /** Retrieval Time */
            retrieval_time: string;
            /** Available At */
            available_at?: string | null;
            /** Eligibility Provenance */
            eligibility_provenance?: string | null;
            /**
             * Units
             * @default USD
             */
            units: string;
            /** Adjusted Open */
            adjusted_open?: number | null;
            /** Adjusted High */
            adjusted_high?: number | null;
            /** Adjusted Low */
            adjusted_low?: number | null;
            /** Adjusted Close */
            adjusted_close?: number | null;
        };
        /** DatasetImportResponse */
        DatasetImportResponse: {
            /** Dataset Version Id */
            dataset_version_id: string;
        };
        /** DefinitionCreateRequest */
        DefinitionCreateRequest: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Definition */
            definition: {
                [key: string]: components["schemas"]["JsonValue-Input"];
            };
        };
        /** DefinitionResponse */
        DefinitionResponse: {
            /** Revision */
            revision: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Definition */
            definition: {
                [key: string]: components["schemas"]["JsonValue-Input"];
            };
        };
        /** DraftResponse */
        DraftResponse: {
            /** Name */
            name: string;
            /** Definition */
            definition: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            };
            /** Saved At */
            saved_at: string;
        };
        /** FundamentalFactResponse */
        FundamentalFactResponse: {
            /** Security Id */
            security_id: string;
            /** Field */
            field: string;
            /** Fiscal Period */
            fiscal_period: string;
            /** Value */
            value: number | string;
            /** Unit */
            unit: string;
            /** Filed At */
            filed_at?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Eligibility Provenance */
            eligibility_provenance?: string | null;
            /** Source */
            source: string;
            /** Retrieval Time */
            retrieval_time: string;
            /** Incomplete Fields */
            incomplete_fields?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        "JsonValue-Input": boolean | number | string | components["schemas"]["JsonValue-Input"][] | {
            [key: string]: components["schemas"]["JsonValue-Input"];
        } | null;
        "JsonValue-Output": boolean | number | string | components["schemas"]["JsonValue-Output"][] | {
            [key: string]: components["schemas"]["JsonValue-Output"];
        } | null;
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Name */
            name: string;
        };
        /** ProjectRenameRequest */
        ProjectRenameRequest: {
            /** Name */
            name: string;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
        };
        /** ProviderDownloadResponse */
        ProviderDownloadResponse: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Version Ids */
            dataset_version_ids: string[];
        };
        /** ResearchThesisResponse */
        ResearchThesisResponse: {
            /** Security Id */
            security_id: string;
            /** Content */
            content: string;
            /** Updated At */
            updated_at?: string | null;
            /** Summary */
            summary?: string | null;
            /** Evidence */
            evidence?: string[];
            /** Risks */
            risks?: string[];
            /** Catalysts */
            catalysts?: string[];
            /** Assumptions */
            assumptions?: string[];
            /** Sources */
            sources?: string[];
            /** Dated Updates */
            dated_updates?: string[];
        };
        /** ResearchThesisSaveRequest */
        ResearchThesisSaveRequest: {
            /** Content */
            content: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** SavedValuationResponse */
        SavedValuationResponse: {
            /** Run Id */
            run_id: string;
            /** Method Revision */
            method_revision: string;
            /** Calculated At */
            calculated_at: string;
            result: components["schemas"]["ComparableValuationResponse"];
        };
        /** SecEdgarDownloadRequest */
        SecEdgarDownloadRequest: {
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provider: "sec_edgar";
            /** Ciks */
            ciks: string[];
        };
        /** SecurityResponse */
        SecurityResponse: {
            /** Security Id */
            security_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
        };
        /** SecuritySummaryResponse */
        SecuritySummaryResponse: {
            security: components["schemas"]["SecurityResponse"];
            /**
             * Daily Bars Count
             * @default 0
             */
            daily_bars_count: number;
            /** Daily Bars Start */
            daily_bars_start?: string | null;
            /** Daily Bars End */
            daily_bars_end?: string | null;
            /** Latest Close */
            latest_close?: number | null;
            /** Daily Bars Dataset Versions */
            daily_bars_dataset_versions?: string[];
            /**
             * Corporate Actions Count
             * @default 0
             */
            corporate_actions_count: number;
            /** Corporate Actions Dataset Versions */
            corporate_actions_dataset_versions?: string[];
            /**
             * Fundamentals Count
             * @default 0
             */
            fundamentals_count: number;
            /** Fundamentals Fiscal Periods */
            fundamentals_fiscal_periods?: string[];
            /** Fundamentals Dataset Versions */
            fundamentals_dataset_versions?: string[];
            /** Covering Dataset Versions */
            covering_dataset_versions?: string[];
            /** Valuations */
            valuations?: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
            /** Runs */
            runs?: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
            /** Alerts */
            alerts?: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
        };
        /** TiingoDownloadRequest */
        TiingoDownloadRequest: {
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provider: "tiingo";
            /** Symbols */
            symbols: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAddRequest */
        WatchlistAddRequest: {
            /** Identifier */
            identifier: string;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            security: components["schemas"]["SecurityResponse"];
            /** Has Thesis */
            has_thesis: boolean;
            /** Thesis Updated At */
            thesis_updated_at?: string | null;
            /** Thesis Preview */
            thesis_preview?: string | null;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /** Project Id */
            project_id: string;
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    download_dataset_api_datasets_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TiingoDownloadRequest"] | components["schemas"]["SecEdgarDownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_definition_api_projects__project_id__definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinitionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_projects__project_id__definitions__kind___name__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                kind: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_api_projects__project_id__definitions__kind___name__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                kind: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_securities_api_securities_get: {
        parameters: {
            query?: {
                /** @description Search symbol or name */
                query?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_comparable_valuation_api_valuations_comparables_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparableValuationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparableValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_comparable_valuation_api_projects__project_id__valuations_comparables_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparableValuationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparableValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_valuations_api_projects__project_id__valuations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedValuationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_details_api_securities__security_id__get: {
        parameters: {
            query?: {
                /** @description Optional Project ID for linked valuations/runs */
                project_id?: string | null;
            };
            header?: never;
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecuritySummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_watchlist_api_projects__project_id__watchlist_get: {
        parameters: {
            query?: {
                /** @description Filter symbol or name */
                query?: string | null;
                /** @description Filter exchange */
                exchange?: string | null;
                /** @description all | has_thesis | no_thesis */
                thesis_status?: string | null;
                /** @description symbol | name | exchange | thesis_updated_at */
                sort_by?: string;
                /** @description asc | desc */
                sort_order?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_project_watchlist_api_projects__project_id__watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_project_watchlist_api_projects__project_id__watchlist__security_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_thesis_api_projects__project_id__research__security_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchThesisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_security_thesis_api_projects__project_id__research__security_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                security_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchThesisSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchThesisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_projects__project_id__runs_post: {
        parameters: {
            query?: {
                dataset_version_id?: string | null;
                historical?: boolean;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"][];
                };
            };
        };
    };
    import_dataset_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_dataset_api_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_datasets__dataset_version_id__coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_preview_api_datasets__dataset_version_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["JsonValue-Output"];
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_history_api_datasets__dataset_version_id__history_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                /** @description As-of decision timestamp (ISO 8601) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyBarResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_fundamentals_api_datasets__dataset_version_id__fundamentals_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                /** @description As-of decision timestamp (ISO 8601) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalFactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_corporate_actions_api_datasets__dataset_version_id__corporate_actions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                /** @description As-of decision timestamp (ISO 8601) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporateActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
